version: '3.7'
services:
  redis:
    image: redis
    container_name: redis_place
    hostname: redis_place
    labels:
      - name=redis
      - mode=standalone
    ports:
      - 6382:6379
    restart: always
    command: redis-server --requirepass "${REDIS_PASSWORD}"